export {default as Header} from './Header/Header';
export {default as Footer} from './Footer/Footer';
export {default as Hero} from './Hero/Hero';
export {default as Product} from './product/Product'
export {default as DisplayProducts} from './displayProducts/DisplayProducts';
export {default as Review} from './Review/Review'
export {default as Steps} from  './proccess/Process'
export {default as CardInput} from './PaymentCardInfo/PaymentCardInfo'
export {default as SearchComponent} from './Search/Search'